(clear-menu)
(add-menu-item "lambda:open-file" "File" "Open File")
(add-menu-item "lambda:open-chrome-file" "File" "Open File with Chrome APIs")
(add-menu-item "lambda:open-folder" "File" "Open Folder")
(add-menu-item "lambda:save-file" "File" "Save File")
(add-menu-item "lambda:save-file-as" "File" "Save File As...")
(add-menu-item "lambda:save-all-files" "File" "Save All Files")
(add-menu-item "lambda:close-file" "File" "Close File")

(add-menu-item "undo" "Edit" "Undo")
(add-menu-item "redo" "Edit" "Redo")
(add-menu-item nil "Edit" nil) ; nil node means a divider
(add-menu-item "find" "Edit" "Find")
(add-menu-item "replace" "Edit" "Find/Replace")
(add-menu-item nil "Edit" nil)
(add-menu-item "togglecomment" "Edit" "Toggle Comment")
(add-menu-item "toggleBlockComment" "Edit" "Toggle Block Comment")
(add-menu-item nil "Edit" nil)
(add-menu-item "sortlines" "Edit" "Sort Lines")
(add-menu-item "joinlines" "Edit" "Join Lines")
(add-menu-item "splitline" "Edit" "Split Line")
(add-menu-item "touppercase" "Edit" "To Uppercase")
(add-menu-item "tolowercase" "Edit" "To Lowercase")
(add-menu-item "movelinesup" "Edit" "Move Lines Up")
(add-menu-item "movelinesdown" "Edit" "Move Lines Down")

;(add-menu-item "sublime:goto" "Tools" "Go To")
(add-menu-item "lambda:command-line" "Tools" "Scheme Command Line")
(add-menu-item "lambda:shell-log" "Tools" "Run Bash Command...")
(add-menu-item "lambda:shell-log-input" "Tools" "Send Input to Process...")

(add-menu-item (lambda () (edit-config 'commands)) "Settings" "Editor Commands")
(add-menu-item (lambda () (edit-config 'bindings)) "Settings" "Key Bindings")
(add-menu-item (lambda () (edit-config 'menus)) "Settings" "Menus")
(add-menu-item (lambda () (edit-config 'preferences)) "Settings" "Preferences")
(add-menu-item (lambda () (edit-config 'theme)) "Settings" "Theme")
(add-menu-item (lambda () (edit-config 'local-config)) "Settings" "Local Settings")
(add-menu-item nil "Settings" nil)
(add-menu-item (lambda () (edit-config 'default-commands)) "Settings" "View Defaults" "Editor Commands")
(add-menu-item (lambda () (edit-config 'default-bindings)) "Settings" "View Defaults" "Key Bindings")
(add-menu-item (lambda () (edit-config 'default-menus)) "Settings" "View Defaults" "Menus")
(add-menu-item (lambda () (edit-config 'default-preferences)) "Settings" "View Defaults" "Preferences")
(add-menu-item (lambda () (edit-config 'default-theme)) "Settings" "View Defaults" "Theme")
