(set! _menus
  (list
    (make-menu "File"
      (list (make-menu "Open File" "lambda:open-file")
            (make-menu "Open File with Chrome APIs" "lambda:open-chrome-file")
            (make-menu "Open Folder" "lambda:open-folder")
            (make-menu "Save File" "lambda:save-file")
            (make-menu "Save File As..." "lambda:save-file-as")
            (make-menu "Save All Files" "lambda:save-all-files")
            (make-menu "Close File" "lambda:close-file")))
    (make-menu "Edit"
      (list (make-menu "Undo" "undo")
            (make-menu "Redo" "redo")
            (make-menu nil nil)
            (make-menu "Find" "find")
            (make-menu "Find/Replace" "replace")
            (make-menu nil nil)
            (make-menu "Toggle Comment" "togglecomment")
            (make-menu "Toggle Block Comment" "toggleBlockComment")
            (make-menu nil nil)
            (make-menu "Sort Lines" "sortlines")
            (make-menu "Join Lines" "joinlines")
            (make-menu "Split Line" "splitline")
            (make-menu "To Uppercase" "touppercase")
            (make-menu "To Lowercase" "tolowercase")
            (make-menu "Move Lines Up" "movelinesup")
            (make-menu "Move Lines Down" "movelinesdown")))
    (make-menu "Tools"
      (list (make-menu "Run Scheme Code..." "lambda:command-line")
            (make-menu "Run Bash Command..." "lambda:shell-log")
            (make-menu "Send Input to Process..." "lambda:shell-log-input")))
    (make-menu "Settings"
      (list (make-menu "Editor Commands" (lambda () (edit-config 'commands)))
            (make-menu "Key Bindings" (lambda () (edit-config 'bindings)))
            (make-menu "Menus" (lambda () (edit-config 'menus)))
            (make-menu "Preferences" (lambda () (edit-config 'preferences)))
            (make-menu "Theme" (lambda () (edit-config 'theme)))
            (make-menu "Local Settings" (lambda () (edit-config 'local-config)))
            (make-menu nil nil)
            (make-menu "View Defaults"
              (list (make-menu "Editor Commands" (lambda () (edit-config 'default-commands)))
                    (make-menu "Key Bindings" (lambda () (edit-config 'default-bindings)))
                    (make-menu "Menus" (lambda () (edit-config 'default-menus)))
                    (make-menu "Preferences" (lambda () (edit-config 'default-preferences)))
                    (make-menu "Theme" (lambda () (edit-config 'default-theme)))))))))
