(set-ace-theme! "monokai")

(define color-light "#eee")
(define color-dark "#222")
(define color-darker-light "#bbb")
(define color-lighter-dark "#444")
(define color-blue "#57f")

(add-css-prop ".toolbar, .sidebar, .tabs, .statusbar" 'background color-dark)
(add-css-prop ".toolbar, .sidebar, .tab-active, .statusbar" 'color color-light)
(add-css-prop ".menu-root:hover, .menu-item, .menu-children" 'background color-light)
(add-css-prop ".menu-root:hover, .menu-item" 'color color-dark)
(add-css-prop ".menu-item:hover" 'background color-darker-light)
(add-css-prop ".menu-subtitle" 'color color-lighter-dark)
(add-css-prop ".tabs" 'color color-darker-light)
(add-css-prop ".tab-active" 'background color-lighter-dark)
(add-css-prop ".tab-indicator" 'background color-blue)
(add-css-prop ".tab-indicator:hover" 'background "#8af")
(add-css-prop ".tab-close:hover" 'background color-light)
(add-css-prop ".tab-close:hover" 'color color-dark)
(add-css-prop ".tab-active" 'border-bottom-color color-blue)
