(define (js-call-on-string str method . args)
  (js-call (js "''." method) 'apply str args))
(define (substring str start end) (js-call-on-string str 'substring start end))
(define (split str delim) (js-call-on-string str 'split delim))
(define (string-replace str find replace) (js-call-on-string str 'replace find replace))
(define (string-length str) (length (split str "")))
(define (string-contains? str search)
    (cond ((> (string-length search) (string-length str)) false)
          ((eq? search (substring str 0 (string-length search))) true)
          (else (string-contains? (substring str 1 (string-length str)) search))))
(define (string-index-of str search start)
    (cond ((> (string-length search) (string-length str)) -1)
          ((eq? search (substring str 0 (string-length search))) start)
          (else (string-index-of (substring str 1 (string-length str)) search (+ start 1)))))
(define (string-lowercase str) (js-call-on-string str "toLowerCase"))
(define (string-uppercase str) (js-call-on-string str "toUpperCase"))
(define (string-char-at str index) (substring str index (+ index 1)))

(hide 'js-call-on-string 'substring 'split 'string-replace 'string-length 'string-contains?
      'string-index-of 'string-lowercase 'string-uppercase 'string-char-at)
